name: ampache

services:
  ampache:
    image: ampache/ampache:latest
    container_name: ampache
    restart: unless-stopped
    ports:
      - 8095:80
    volumes:
      - /var/www/config:/var/www/config
      - /var/log/ampache:/var/log/ampache
      - /media/devmon/COLTER_FILMS/music:/media
      - /var/lib/mysql:/var/lib/mysql
    environment:
      DISABLE_INOTIFYWAIT_CLEAN: ${DISABLE_INOTIFYWAIT_CLEAN-0}

# chgrp 33 /media/devmon/COLTER_FILMS/music && chmod g+w /media/devmon/COLTER_FILMS/music