services:
    beets-flask:
        image: pspitzner/beets-flask:stable
        container_name: beets-flask
        restart: unless-stopped
        ports:
            - 5001:5001
        environment:
            TZ: Auckland/Pacific
            USER_ID: 1000
            GROUP_ID: 1000
        volumes:
            - /DATA/AppData/beets/config/:/config
            - /mnt/media/music/soulseek/beets-inbox/:/soulseek/inbox/
            - /mnt/media/music/soulseek/beets-clean/:/soulseek/clean/
            - /mnt/media/music/telegram_bot/beets-clean:/telegram_bot/beets-clean

