services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    # environment:
    #   # Optional: put your config options customization here. Examples:
    #   # ND_LOGLEVEL: debug
    volumes:
      - "/DATA/AppData/navidrome:/data"
      - "/media/devmon/COLTER_T7/DJ MUSIC:/music:ro"