version: '3'
services:
  picard:
    image: mikenye/picard:latest
    container_name: picard
    ports:
      - 5800:5800
    volumes:
      - /DATA/AppData/picard/config:/config:rw
      - /mnt/media:/storage:rw

