---
version: "2"
services:
  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    network_mode: container:gluetun
    ports:
      # - "5030:5030"
      # - "5031:5031"
      # - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - /DATA/AppData/soulseek:/app
      - /media/devmon/COLTER_T7/"DJ MUSIC":/music
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    restart: always